[package]
name = "sp-circuits"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ec = "0.4.2"
ark-secp256k1 = "0.4.0"
frontend = { git = "https://github.com/personaelabs/shockwave-plus" }
shockwave-plus = { git = "https://github.com/personaelabs/shockwave-plus" }
